export const SHOW_OR_HIDE = 'SHOW_OR_HIDE';

export const BOARD_FETCHING_START = 'BOARD_FETCHING_START';
export const BOARD_FETCHING_SUCCESS = "BOARD_FETCHING_SUCCESS";
export const BOARD_FETCHING_FAILURE = 'BOARD_FETCHING_FAILURE';

export const OUTLINE_FETCHING_START = 'OUTLINE_FETCHING_START';
export const OUTLINE_FETCHING_SUCCESS = "OUTLINE_FETCHING_SUCCESS";
export const OUTLINE_FETCHING_FAILURE = 'OUTLINE_FETCHING_FAILURE';

export const MODEL_2D_FETCHING_START = 'MODEL_2D_FETCHING_START';
export const MODEL_2D_FETCHING_SUCCESS = "MODEL_2D_FETCHING_SUCCESS";
export const MODEL_2D_FETCHING_FAILURE = 'MODEL_2D_FETCHING_FAILURE';

export const COMPONENTS_FETCHING_START = 'COMPONENTS_FETCHING_START';
export const COMPONENTS_FETCHING_SUCCESS = "COMPONENTS_FETCHING_SUCCESS";
export const COMPONENTS_FETCHING_FAILURE = 'COMPONENTS_FETCHING_FAILURE';

export const CAD_IMAGES_START = 'CAD_IMAGES_START';
export const CAD_IMAGES_SUCCESS = "CAD_IMAGES_SUCCESS";
export const CAD_IMAGES_FAILURE = "CAD_IMAGES_FAILURE";

export const CAD_MTL_START = 'CAD_MTL_START';
export const CAD_MTL_SUCCESS = "CAD_MTL_SUCCESS";
export const CAD_MTL_FAILURE = "CAD_MTL_FAILURE";